# Este es un docker-compose enfocado en Desarrollo.
# Usamos .env para configuración local

services:
  db:
    image: postgres:16-alpine
    container_name: ${CONTAINER_DB}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ${CONTAINER_SERVER}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    # monta tu directorio local dentro del contenedor, esto permite la sincronización en tiempo real de los cambios en el código
    volumes:
      - ./backend/src:/app/src
    # Reinicia el contenedor si falla, para recuperarse de errores inesperados
    restart: on-failure

volumes:
  db_data:
