# Utiliza una imagen de Node.js más ligera enfocada en desarrollo
FROM node:22.14.0-slim

# Instala herramientas útiles para el desarrollo
RUN apt-get update && apt-get install -y --no-install-recommends \
  # tener inotify-tools puede ser útil en algunos escenarios o para depuración.
  inotify-tools \
  git \
  && rm -rf /var/lib/apt/lists/*

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia solo los archivos de configuración para instalar dependencias rápidamente
COPY package-lock.json ./
COPY package.json ./

# Instala las dependencias (sin la bandera --production para incluir devDependencies)
RUN npm install

# Copia el resto de los archivos de la aplicación (se montará un volumen para esto)
COPY . .

# Expone el puerto que tu aplicación Astro utiliza
EXPOSE 4321

# Define el comando para iniciar la aplicación en modo desarrollo
CMD ["npm", "run", "dev", "--", "--host", "--open"]